### ISSUE TITLE
secrets NPM_TOKEN

### ISSUE THREAD

**Issue by Viserion77** [Adapcon/vue-polar-bear#277]
https://github.com/Adapcon/vue-polar-bear/blob/ef6bb9a47db74fc7ad3e4e3d9401cc7ff96e4b12/.github/workflows/master.yml#L19

Salve galerinha!

Este token esta em meus dominios, seria otimo trocar para a conta da adap no npm:
```
login: adapcon
senha: ta lá na tela de senhas no csw, ou no meu privado :eyes:
```

[Genrete a token on npm](https://www.npmjs.com/settings/adapcon/tokens)

🤘🏼

**Comment by mickaelnn** [comment]
Realizei o cadastro na nova token
